"""Add first_login column to User model

Revision ID: 5a5921518412
Revises: 5ca8913068e5
Create Date: 2025-07-23 22:55:51.278120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5921518412'
down_revision = '5ca8913068e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_login', sa.Boolean(), nullable=True))
        
    # Set default value for existing users
    op.execute("UPDATE users SET first_login = false")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_login')

    # ### end Alembic commands ###